apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx_depl
  name: nginx_depl
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx_depl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx_depl
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
